# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

articles = Article.create([{ author: "Firdose Moonda", title: "Domingo reapplies to be South Africa coach", des: "Russell Domingo has confirmed he has reapplied to be South Africa's coach when his contract expires in August, at the end of the England tour", url: "http://www.espncricinfo.com/southafrica/content/story/1108297.html", url_to_image: "http://a.espncdn.com/combiner/i?img=/media/motion/2017/0703/dm_170703_CRIC_DOMINGO_INTERVIEW/dm_170703_CRIC_DOMINGO_INTERVIEW.jpg?w=1244&h=700" },
 { author: "ESPNcricinfo staff", title: "Kycia Knight, Subrina Munroe added to West Indies squad", des: "Batsman and seamer come in place of injured fast bowlers Shakera Selman and Shamilia Connell", url: "http://www.espncricinfo.com/icc-womens-world-cup-2017/content/story/1108278.html", url_to_image: "http://www.espncricinfo.com/db/PICTURES/CMS/225700/225711.3.jpg" },
 { author: "Firdose Moonda", title: "Du Plessis misses Lord's; Elgar captains", des: "Faf du Plessis will miss the opening Test against England at Lord's to remain with his wife after the 'difficult' birth of their first child", url: "http://www.espncricinfo.com/england-v-south-africa-2017/content/story/1108264.html", url_to_image: "http://a.espncdn.com/combiner/i?img=/media/motion/2017/0703/dm_170703_CRIC_JUL3_ENGVSA_int_Richards_Elgar_GLOBAL/dm_170703_CRIC_JUL3_ENGVSA_int_Richards_Elgar_GLOBAL.jpg?w=1244&h=700" },
 { author: "ESPNcricinfo staff", title: "Kesrick Williams did an outstanding job - Holder", des: "Captain Jason Holder and coach Stuart Law hoped that West Indies' stunning win against India in the fourth ODI would be a stepping stone to higher honours", url: "http://www.espncricinfo.com/west-indies-v-india-2017/content/story/1108263.html", url_to_image: "http://a.espncdn.com/combiner/i?img=/media/motion/2017/0703/dm_170703_PC_030717_StuartLaw_GLO/dm_170703_PC_030717_StuartLaw_GLO.jpg?w=1244&h=700" }, 
 { author: "David Hopps", title: "Somerset drop Abell as young captain seeks form", des: "Tom Abell, Somerset's talented but beleaguered young captain, has been dropped for Somerset's Championship match against Yorkshire at Scarborough", url: "http://www.espncricinfo.com/county-cricket-2017/content/story/1108261.html", url_to_image: "http://www.espncricinfo.com/db/PICTURES/CMS/256600/256602.3.jpg" }, 
 { author: "Daniel Brettig", title: "Sutherland refuses to intervene in pay dispute", des: "Cricket Australia chief executive James Sutherland has declined to intervene in the pay dispute between the board and the Australian Cricketers' Association on his return to the head office last week", url: "http://www.espncricinfo.com/australia/content/story/1108258.html", url_to_image: "http://www.espncricinfo.com/db/PICTURES/CMS/205300/205351.jpg" }, 
 { author: "ESPNcricinfo staff", title: "Our shot selection wasn't up to the mark - Kohli", des: "Virat Kohli and Sanjay Bangar have said the shot selection of India's batsmen, and lack of support for MS Dhoni from the lower order cost them in the fourth ODI in Antigua", url: "http://www.espncricinfo.com/west-indies-v-india-2017/content/story/1108240.html", url_to_image: "http://a.espncdn.com/combiner/i?img=/media/motion/2017/0703/dm_170703_PC_030717_Bangar_GLO/dm_170703_PC_030717_Bangar_GLO.jpg?w=1244&h=700" }, 
 { author: "ESPNcricinfo staff", title: "Was waiting for this opportunity - Sushma Verma", des: "India women's wicketkeeper-batsman Sushma Verma, who hardly got batting opportunities in the past, cashed in on the chance against Pakistan with a 35-ball 33", url: "http://www.espncricinfo.com/icc-womens-world-cup-2017/content/story/1108233.html", url_to_image: "http://a.espncdn.com/combiner/i?img=/media/motion/2017/0702/dm_170702_CRIC_WWC17_RAJ_PC_NRH/dm_170702_CRIC_WWC17_RAJ_PC_NRH.jpg?w=1244&h=700" }, 
 { author: "ESPNcricinfo staff", title: "Jonassen, Perry star in Australia's third win", des: "Ellyse Perry's 91-ball 71 formed the bedrock of Australia's 220 chase, which they saw off with five wickets in hand in the penultimate over", url: "http://www.espncricinfo.com/icc-womens-world-cup-2017/content/story/1108169.html", url_to_image: "http://www.espncricinfo.com/db/PICTURES/CMS/265200/265209.jpg" }, 
 { author: "Nagraj Gollapudi", title: "Jaitley warns BCCI against stubborn stance", des: "The prospect of the BCCI adopting the Lodha Committee recommendations is now stronger as Arun Jaitley, the Indian finance minister and an eminent lawyer, has asked the board to not confront Supreme Court", url: "http://www.espncricinfo.com/india/content/story/1108167.html", url_to_image: "http://www.espncricinfo.com/db/PICTURES/CMS/158600/158627.3.jpg" }])